# Generated by Django 3.2.13 on 2022-07-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220705_2134'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_relationships',
        ),
    ]
